chuangmi.camera.019e04:
  channel_count: 1
  name: 小白智能摄像机A1母婴版
  vendor: 上海创米科技
chuangmi.camera.021a04:
  channel_count: 1
  name: 小米智能摄像机云台版Pro
  vendor: 上海创米科技
chuangmi.camera.021e02:
  channel_count: 1
  name: 小白智能摄像机A2
  vendor: 上海创米科技
chuangmi.camera.025b02:
  channel_count: 1
  name: 小白智能摄像机 户外云台版 N系列
  vendor: 上海创米科技
chuangmi.camera.026c02:
  channel_count: 1
  name: 小米智能摄像机云台版SE+
  vendor: 上海创米科技
chuangmi.camera.029a02:
  channel_count: 1
  name: 小米智能摄像机 云台版2K
  vendor: 上海创米科技
chuangmi.camera.036a02:
  channel_count: 1
  name: 小白智能摄像机 云台版Y2
  vendor: 上海创米科技
chuangmi.camera.038a02:
  channel_count: 1
  name: 小白智能摄像机Y2 云台尊享版
  vendor: 上海创米科技
chuangmi.camera.039a01:
  channel_count: 1
  name: 小米智能摄像机2 云台版
  vendor: 上海创米科技
chuangmi.camera.039c01:
  channel_count: 1
  name: 小米智能摄像机2 云台版
  vendor: 上海创米科技
chuangmi.camera.040a02:
  channel_count: 1
  name: 小白智能户外摄像机 AI高清版
  vendor: 上海创米科技
chuangmi.camera.042a02:
  channel_count: 1
  name: 小白智能摄像机 户外云台版N4
  vendor: 上海创米科技
chuangmi.camera.046b02:
  channel_count: 1
  name: 小白智能摄像机 云台版Y2
  vendor: 上海创米科技
chuangmi.camera.046c04:
  channel_count: 1
  name: 小米智能摄像机 云台版SE+
  vendor: 上海创米科技
chuangmi.camera.046d02:
  channel_count: 1
  name: 小白智能摄像机 云台版Y2
  vendor: 上海创米科技
chuangmi.camera.049a01:
  channel_count: 1
  name: 小米智能摄像机2 云台版
  vendor: 上海创米科技
chuangmi.camera.051a01:
  channel_count: 1
  name: 小米智能摄像机2 AI增强版
  vendor: 上海创米科技
chuangmi.camera.055a02:
  channel_count: 1
  name: 小白智能全景球机 Q1
  vendor: 上海创米科技
chuangmi.camera.055c02:
  channel_count: 1
  name: 小白智能全景球机 Q1
  vendor: 上海创米科技
chuangmi.camera.060a02:
  channel_count: 1
  name: 小白智能摄像机
  vendor: 上海创米科技
chuangmi.camera.061a01:
  channel_count: 1
  name: 小米智能摄像机3 Pro 云台版
  vendor: 上海创米科技
chuangmi.camera.065ac1:
  channel_count: 1
  name: 小白智能户外摄像机Q2
  vendor: 上海创米科技
chuangmi.camera.066a01:
  channel_count: 1
  name: 小米智能摄像机 母婴看护版
  vendor: 上海创米科技
chuangmi.camera.068ac1:
  channel_count: 2
  name: 小白智能户外摄像机Q2 双摄照明版
  vendor: 上海创米科技
chuangmi.camera.069a01:
  channel_count: 1
  name: 小米智能摄像机3 云台版
  vendor: 上海创米科技
chuangmi.camera.070a02:
  channel_count: 1
  name: 小白智能摄像机
  vendor: 上海创米科技
chuangmi.camera.079ac1:
  channel_count: 1
  name: 小米智能摄像机 4
  vendor: 上海创米科技
chuangmi.camera.086ac1:
  channel_count: 1
  name: 小米智能摄像机 视频通话版
  vendor: 上海创米科技
chuangmi.camera.111ac1:
  channel_count: 2
  name: 小白智能摄像机 A2双摄版
  vendor: 上海创米科技
chuangmi.camera.27a02:
  channel_count: 1
  name: 小白智能摄像机大众版C1
  vendor: 上海创米科技
chuangmi.camera.46e01:
  channel_count: 1
  name: 小白智能摄像机 (2.5K)
  vendor: 上海创米科技
chuangmi.camera.72ac1:
  channel_count: 2
  name: 小米智能摄像机C300双摄版
  vendor: 上海创米科技
chuangmi.camera.81ac1:
  channel_count: 1
  name: 小米智能摄像机C700
  vendor: 上海创米科技
chuangmi.camera.ip026c:
  channel_count: 1
  name: 小米智能摄像机 云台版SE
  vendor: 上海创米科技
chuangmi.camera.ip029a:
  channel_count: 1
  name: 小米智能摄像机 云台版2K
  vendor: 上海创米科技
chuangmi.camera.ipc021:
  channel_count: 1
  name: 小米智能摄像机  云台版Pro
  vendor: 上海创米科技
chuangmi.camera.ipc022:
  channel_count: 1
  name: 小米智能摄像机 AI探索版
  vendor: 上海创米科技
isa.camera.cw500:
  channel_count: 1
  name: 小米室外摄像机CW500
  vendor: 天津华来科技有限公司
isa.camera.cw501d:
  channel_count: 2
  name: 小米室外摄像机 4 双摄版
  vendor: 天津华来科技有限公司
isa.camera.hlc6:
  channel_count: 1
  name: 小米智能摄像机 标准版
  vendor: 天津华来科技有限公司
isa.camera.hlc7:
  channel_count: 1
  name: 小米智能摄像机 标准版2K
  vendor: 天津华来科技有限公司
isa.camera.hlc8:
  channel_count: 1
  name: Xiaomi室外摄像机CW400
  vendor: 天津华来科技有限公司
isa.camera.hlmax:
  channel_count: 2
  name: 小米室外摄像机CW500双摄版
  vendor: 天津华来科技有限公司
isa.camera.hlv3c:
  channel_count: 1
  name: 华来小方室外摄像机 2K版
  vendor: 天津华来科技有限公司
isa.camera.hlzoom:
  channel_count: 1
  name: 小米室外摄像机CW700S
  vendor: 天津华来科技有限公司
isa.camera.panjd1:
  channel_count: 1
  name: 小方智能摄像机 云台版
  vendor: 天津华来科技有限公司
mxiang.camera.c500ch:
  channel_count: 2
  name: 小米智能摄像机C500双摄版
  vendor: 上海摩象网络科技有限公司
mxiang.camera.moc001:
  channel_count: 1
  name: 小米室外摄像机CW300
  vendor: 上海摩象网络科技有限公司
mxiang.camera.mod11:
  channel_count: 1
  name: Xiaomi室外摄像机 AW300
  vendor: 上海摩象网络科技有限公司
mxiang.camera.mwc10:
  channel_count: 1
  name: 小米室外摄像机电池版（室内机）
  vendor: 上海摩象网络科技有限公司
mxiang.camera.mwc11:
  channel_count: 1
  name: 小米室外摄像机电池版（摄像机）
  vendor: 上海摩象网络科技有限公司
xiaomi.camera.c01a02:
  channel_count: 1
  name: 小米智能摄像机 云台版2K
  vendor: 小米
xiaomi.camera.c302:
  channel_count: 1
  name: 小米室外摄像机 4C 3.5K
  vendor: 小米
xiaomi.camera.cw301:
  channel_count: 1
  name: 小米室外摄像机 4C
  vendor: 小米
